org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

#Mod informations
mod_id=civiliansmod
mod_name=Civilians
mod_version=v1.4.2

maven_group=net.asian.civilians
archives_base_name=civiliansmod
mod_description=Civilians is a great way to bring your survival/creative world to another level. Let's say you are working on a city, town, village, etc. Similar to how villagers are in Minecraft villages, Civilians will make it come alive!

#MC Fabric
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.18.4
loom_version=1.11-SNAPSHOT

#Fabric API
fabric_version=0.128.2+1.21.5

#modrinth_release_type=release
#modrinth_project_id=8RYPaw1l
#modrinth_api_token=Never put your token here!

#curseforge_release_type=release
#curseforge_project_id=1170845
#curseforge_api_token=Never put your token here!